# This is the configuration file for your Cloudflare Worker.

name = "gen2mail5-bot"  # သင် Cloudflare မှာပေးထားတဲ့ Project နာမည်ကို ဒီမှာထည့်ပါ
main = "worker.js"     # သင့် Javascript file ရဲ့ နာမည်ကို ဒီမှာထည့်ပါ

compatibility_date = "2024-07-25" # ဒီရက်စွဲကို ဒီအတိုင်းထားနိုင်ပါသည်
